baseURL = 'https://jirathip-k.github.io/'
languageCode = 'en-us'
title = 'Jirathip'

[taxonomies]
  content = 'contents'
  project = 'projects'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
